language: python
python:
  - "2.7"
env:
  - DJANGO=1.8
install:
  - pip install -q Django==$DJANGO --quiet --use-mirrors
  - pip install pep8 --quiet --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master --quiet --use-mirrors
  - pip install -r requirements.txt --quiet --use-mirrors
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 ."
  - pyflakes -x W .
script:
  - python manage.py test
